# Generated by Django 5.0.4 on 2024-05-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Чуй', 'Чуй'), ('Талас', 'Талас'), ('Иссык-Куль', 'Иссык-Куль'), ('Нарын', 'Нарын'), ('Жалал-Абад', 'Жалал-Абад'), ('Ош', 'Ош'), ('Баткен', 'Баткен')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type_of_event', models.CharField(choices=[('Открытие', 'Открытие'), ('Выставка', 'Выставка'), ('Ярмарка', 'Ярмарка'), ('Презентация', 'Презентация'), ('Праздник', 'Праздник'), ('Пресс-мероприятие', 'Пресс-мероприятие'), ('Тренинг/семинар', 'Тренинг/семинар'), ('Фестиваль/концерт', 'Фестиваль/концерт')], max_length=50)),
                ('type', models.CharField(choices=[('Открытый', 'Открытый'), ('Закрытый', 'Закрытый')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.events')),
            ],
        ),
    ]
