# Generated by Django 5.0.6 on 2024-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('Вход свободный', 'Вход свободный'), ('Вход закрытый', 'Вход закрытый')], max_length=50),
        ),
    ]
