# Generated by Django 5.0.6 on 2024-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
