# Generated by Django 5.1.5 on 2025-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
